---
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
extends:
  - 'plugin:@typescript-eslint/recommended'
  - eslint-config-prettier
rules:
  no-unused-vars:
    - warn
  '@typescript-eslint/member-delimiter-style':
    - warn
    - multiline:
        delimiter: none
  '@typescript-eslint/ban-types':
    - off
  '@typescript-eslint/no-explicit-any':
    - off
  '@typescript-eslint/no-extra-semi':
    - off
